<?php
declare(strict_types=1);

/**
 * Generate SQL seed statements for districts/schools from a CSV master list.
 *
 * Usage:
 *   php scripts/generate_school_seed.php input.csv output.sql
 *
 * Expected CSV headers (case-insensitive; common aliases are supported):
 *   district, school
 */

if ($argc < 3) {
    fwrite(STDERR, "Usage: php scripts/generate_school_seed.php <input.csv> <output.sql>\n");
    exit(1);
}

$inputPath = $argv[1];
$outputPath = $argv[2];

if (!is_file($inputPath)) {
    fwrite(STDERR, "Input file not found: {$inputPath}\n");
    exit(1);
}

$handle = fopen($inputPath, 'rb');
if ($handle === false) {
    fwrite(STDERR, "Unable to open input file: {$inputPath}\n");
    exit(1);
}

$headers = fgetcsv($handle);
if ($headers === false) {
    fclose($handle);
    fwrite(STDERR, "Input CSV is empty.\n");
    exit(1);
}

$normalizedHeaders = [];
foreach ($headers as $index => $header) {
    $key = strtolower(trim((string)$header));
    $normalizedHeaders[$key] = $index;
}

$districtHeaderCandidates = ['district', 'district_name', 'district name', 'division_district'];
$schoolHeaderCandidates = ['school', 'school_name', 'school name', 'school_office', 'organization'];

$districtColumn = null;
$schoolColumn = null;

foreach ($districtHeaderCandidates as $candidate) {
    if (array_key_exists($candidate, $normalizedHeaders)) {
        $districtColumn = $normalizedHeaders[$candidate];
        break;
    }
}
foreach ($schoolHeaderCandidates as $candidate) {
    if (array_key_exists($candidate, $normalizedHeaders)) {
        $schoolColumn = $normalizedHeaders[$candidate];
        break;
    }
}

if ($districtColumn === null || $schoolColumn === null) {
    fclose($handle);
    fwrite(
        STDERR,
        "Missing required headers. Required logical headers: district + school.\n" .
        "Accepted district headers: " . implode(', ', $districtHeaderCandidates) . "\n" .
        "Accepted school headers: " . implode(', ', $schoolHeaderCandidates) . "\n"
    );
    exit(1);
}

$districts = [];
$schoolsByDistrict = [];
$lineNumber = 1;

while (($row = fgetcsv($handle)) !== false) {
    $lineNumber += 1;

    $district = isset($row[$districtColumn]) ? trim((string)$row[$districtColumn]) : '';
    $school = isset($row[$schoolColumn]) ? trim((string)$row[$schoolColumn]) : '';

    if ($district === '' || $school === '') {
        continue;
    }

    if (!isset($districts[$district])) {
        $districts[$district] = true;
        $schoolsByDistrict[$district] = [];
    }

    $schoolsByDistrict[$district][$school] = true;
}
fclose($handle);

if (empty($districts)) {
    fwrite(STDERR, "No valid district/school rows found in input file.\n");
    exit(1);
}

ksort($districts, SORT_NATURAL | SORT_FLAG_CASE);
ksort($schoolsByDistrict, SORT_NATURAL | SORT_FLAG_CASE);
foreach ($schoolsByDistrict as $district => $schools) {
    ksort($schools, SORT_NATURAL | SORT_FLAG_CASE);
    $schoolsByDistrict[$district] = array_keys($schools);
}

$escape = static function (string $value): string {
    return str_replace("'", "''", $value);
};

$lines = [];
$lines[] = '-- Generated by scripts/generate_school_seed.php';
$lines[] = '-- Source: ' . $inputPath;
$lines[] = '-- Date: ' . date('Y-m-d H:i:s');
$lines[] = '';
$lines[] = '-- District seed upserts';
$lines[] = 'INSERT INTO districts (name) VALUES';

$districtValues = [];
foreach (array_keys($districts) as $districtName) {
    $districtValues[] = "('" . $escape($districtName) . "')";
}
$lines[] = implode(",\n", $districtValues);
$lines[] = 'ON DUPLICATE KEY UPDATE name = VALUES(name);';
$lines[] = '';
$lines[] = '-- School seed upserts';
$lines[] = 'INSERT INTO schools (district_id, name)';
$lines[] = 'SELECT d.id, x.school_name';
$lines[] = 'FROM districts d';
$lines[] = 'JOIN (';

$schoolRows = [];
foreach ($schoolsByDistrict as $districtName => $schools) {
    foreach ($schools as $schoolName) {
        $schoolRows[] =
            "    SELECT '" . $escape($districtName) . "' AS district_name, '" . $escape($schoolName) . "' AS school_name";
    }
}
$lines[] = implode("\n    UNION ALL\n", $schoolRows);
$lines[] = ') x ON x.district_name = d.name';
$lines[] = 'ON DUPLICATE KEY UPDATE name = VALUES(name);';
$lines[] = '';

$sql = implode("\n", $lines);

$result = file_put_contents($outputPath, $sql);
if ($result === false) {
    fwrite(STDERR, "Unable to write output file: {$outputPath}\n");
    exit(1);
}

fwrite(
    STDOUT,
    "Generated {$outputPath} with " . count($districts) . " districts and " . count($schoolRows) . " schools.\n"
);
exit(0);
