-- Generated by scripts/generate_school_seed.php
-- Source: docs\school_master_template.csv
-- Date: 2026-02-11 06:04:23

-- District seed upserts
INSERT INTO districts (name) VALUES
('Bontoc I District'),
('Maasin City District')
ON DUPLICATE KEY UPDATE name = VALUES(name);

-- School seed upserts
INSERT INTO schools (district_id, name)
SELECT d.id, x.school_name
FROM districts d
JOIN (
    SELECT 'Bontoc I District' AS district_name, 'Bontoc I Central School' AS school_name
    UNION ALL
    SELECT 'Bontoc I District' AS district_name, 'Bontoc I National High School' AS school_name
    UNION ALL
    SELECT 'Maasin City District' AS district_name, 'Maasin City Central School' AS school_name
    UNION ALL
    SELECT 'Maasin City District' AS district_name, 'Maasin City National High School' AS school_name
) x ON x.district_name = d.name
ON DUPLICATE KEY UPDATE name = VALUES(name);
